// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Getway.proto

#include "Getway.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace Getway {
class ServerRegisterDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ServerRegister>
      _instance;
} _ServerRegister_default_instance_;
class MessageErrorDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MessageError>
      _instance;
} _MessageError_default_instance_;
}  // namespace Getway
namespace protobuf_Getway_2eproto {
static void InitDefaultsServerRegister() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Getway::_ServerRegister_default_instance_;
    new (ptr) ::Getway::ServerRegister();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Getway::ServerRegister::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ServerRegister =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsServerRegister}, {}};

static void InitDefaultsMessageError() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Getway::_MessageError_default_instance_;
    new (ptr) ::Getway::MessageError();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Getway::MessageError::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MessageError =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMessageError}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ServerRegister.base);
  ::google::protobuf::internal::InitSCC(&scc_info_MessageError.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Getway::ServerRegister, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Getway::ServerRegister, type_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Getway::MessageError, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Getway::MessageError, error_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Getway::ServerRegister)},
  { 6, -1, sizeof(::Getway::MessageError)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Getway::_ServerRegister_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Getway::_MessageError_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "Getway.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014Getway.proto\022\006Getway\"2\n\016ServerRegister"
      "\022 \n\004type\030\001 \001(\0162\022.Getway.ServerType\"\211\001\n\014M"
      "essageError\022-\n\005error\030\001 \001(\0162\036.Getway.Mess"
      "ageError.ErrorType\"J\n\tErrorType\022\016\n\nHASH_"
      "ERROR\020\000\022\030\n\024MESSAGE_FORMAT_ERROR\020\001\022\023\n\017CHE"
      "CK_SUM_ERROR\020\002*\"\n\nServerType\022\t\n\005LOGIN\020\000\022"
      "\t\n\005LOBBY\020\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 258);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Getway.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_Getway_2eproto
namespace Getway {
const ::google::protobuf::EnumDescriptor* MessageError_ErrorType_descriptor() {
  protobuf_Getway_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Getway_2eproto::file_level_enum_descriptors[0];
}
bool MessageError_ErrorType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const MessageError_ErrorType MessageError::HASH_ERROR;
const MessageError_ErrorType MessageError::MESSAGE_FORMAT_ERROR;
const MessageError_ErrorType MessageError::CHECK_SUM_ERROR;
const MessageError_ErrorType MessageError::ErrorType_MIN;
const MessageError_ErrorType MessageError::ErrorType_MAX;
const int MessageError::ErrorType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* ServerType_descriptor() {
  protobuf_Getway_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Getway_2eproto::file_level_enum_descriptors[1];
}
bool ServerType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void ServerRegister::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ServerRegister::kTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ServerRegister::ServerRegister()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_Getway_2eproto::scc_info_ServerRegister.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Getway.ServerRegister)
}
ServerRegister::ServerRegister(const ServerRegister& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:Getway.ServerRegister)
}

void ServerRegister::SharedCtor() {
  type_ = 0;
}

ServerRegister::~ServerRegister() {
  // @@protoc_insertion_point(destructor:Getway.ServerRegister)
  SharedDtor();
}

void ServerRegister::SharedDtor() {
}

void ServerRegister::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ServerRegister::descriptor() {
  ::protobuf_Getway_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Getway_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ServerRegister& ServerRegister::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_Getway_2eproto::scc_info_ServerRegister.base);
  return *internal_default_instance();
}


void ServerRegister::Clear() {
// @@protoc_insertion_point(message_clear_start:Getway.ServerRegister)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  type_ = 0;
  _internal_metadata_.Clear();
}

bool ServerRegister::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Getway.ServerRegister)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Getway.ServerType type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::Getway::ServerType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Getway.ServerRegister)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Getway.ServerRegister)
  return false;
#undef DO_
}

void ServerRegister::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Getway.ServerRegister)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Getway.ServerType type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Getway.ServerRegister)
}

::google::protobuf::uint8* ServerRegister::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Getway.ServerRegister)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Getway.ServerType type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Getway.ServerRegister)
  return target;
}

size_t ServerRegister::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Getway.ServerRegister)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .Getway.ServerType type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ServerRegister::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Getway.ServerRegister)
  GOOGLE_DCHECK_NE(&from, this);
  const ServerRegister* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ServerRegister>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Getway.ServerRegister)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Getway.ServerRegister)
    MergeFrom(*source);
  }
}

void ServerRegister::MergeFrom(const ServerRegister& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Getway.ServerRegister)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.type() != 0) {
    set_type(from.type());
  }
}

void ServerRegister::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Getway.ServerRegister)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ServerRegister::CopyFrom(const ServerRegister& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Getway.ServerRegister)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServerRegister::IsInitialized() const {
  return true;
}

void ServerRegister::Swap(ServerRegister* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ServerRegister::InternalSwap(ServerRegister* other) {
  using std::swap;
  swap(type_, other->type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ServerRegister::GetMetadata() const {
  protobuf_Getway_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Getway_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MessageError::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MessageError::kErrorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MessageError::MessageError()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_Getway_2eproto::scc_info_MessageError.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Getway.MessageError)
}
MessageError::MessageError(const MessageError& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  error_ = from.error_;
  // @@protoc_insertion_point(copy_constructor:Getway.MessageError)
}

void MessageError::SharedCtor() {
  error_ = 0;
}

MessageError::~MessageError() {
  // @@protoc_insertion_point(destructor:Getway.MessageError)
  SharedDtor();
}

void MessageError::SharedDtor() {
}

void MessageError::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MessageError::descriptor() {
  ::protobuf_Getway_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Getway_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MessageError& MessageError::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_Getway_2eproto::scc_info_MessageError.base);
  return *internal_default_instance();
}


void MessageError::Clear() {
// @@protoc_insertion_point(message_clear_start:Getway.MessageError)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  error_ = 0;
  _internal_metadata_.Clear();
}

bool MessageError::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Getway.MessageError)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Getway.MessageError.ErrorType error = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_error(static_cast< ::Getway::MessageError_ErrorType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Getway.MessageError)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Getway.MessageError)
  return false;
#undef DO_
}

void MessageError::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Getway.MessageError)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Getway.MessageError.ErrorType error = 1;
  if (this->error() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->error(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Getway.MessageError)
}

::google::protobuf::uint8* MessageError::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Getway.MessageError)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Getway.MessageError.ErrorType error = 1;
  if (this->error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->error(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Getway.MessageError)
  return target;
}

size_t MessageError::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Getway.MessageError)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .Getway.MessageError.ErrorType error = 1;
  if (this->error() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->error());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MessageError::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Getway.MessageError)
  GOOGLE_DCHECK_NE(&from, this);
  const MessageError* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MessageError>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Getway.MessageError)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Getway.MessageError)
    MergeFrom(*source);
  }
}

void MessageError::MergeFrom(const MessageError& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Getway.MessageError)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.error() != 0) {
    set_error(from.error());
  }
}

void MessageError::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Getway.MessageError)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageError::CopyFrom(const MessageError& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Getway.MessageError)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageError::IsInitialized() const {
  return true;
}

void MessageError::Swap(MessageError* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MessageError::InternalSwap(MessageError* other) {
  using std::swap;
  swap(error_, other->error_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MessageError::GetMetadata() const {
  protobuf_Getway_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Getway_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Getway
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Getway::ServerRegister* Arena::CreateMaybeMessage< ::Getway::ServerRegister >(Arena* arena) {
  return Arena::CreateInternal< ::Getway::ServerRegister >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Getway::MessageError* Arena::CreateMaybeMessage< ::Getway::MessageError >(Arena* arena) {
  return Arena::CreateInternal< ::Getway::MessageError >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
